### ISSUE TITLE
Create Categories - Upon editing a category you are able to set the parent category as itself. 

### ISSUE THREAD

**Issue by darrengeary** [shopizer-ecommerce/shopizer-admin#36]
The parent field should not allow the current entity to be an option, if this is chosen the category will disappear from the category list but still exists in storage.

**Comment by shopizer-ecommerce** [comment]
Fixed

https://github.com/shopizer-ecommerce/shopizer-admin/commit/f232cf9e0251430629963bc9b9bdb8128a47da3d

**Comment by shopizer-ecommerce** [comment]
Fixed

https://github.com/shopizer-ecommerce/shopizer-admin/commit/f232cf9e0251430629963bc9b9bdb8128a47da3d
